name: python

on: pull_request

env:
  APP_API_KEY: ${{ secrets.APP_API_KEY }}
  ENABLE_HOPSWORKS_USAGE: "false"

jobs:
  unit_tests_ubuntu_utc:
    name: Unit Testing (Ubuntu)
    needs: lint_stylecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone UTC

      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e python[python,dev]

      - name: Display Python version
        run: python --version

      - name: Run Pytest suite
        run: pytest python/tests

  unit_tests_ubuntu_pandas:
    name: Unit Testing (Ubuntu) (Pandas 1.x)
    needs: lint_stylecheck
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone UTC

      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e python[python,dev-pandas1]

      - name: Display Python version
        run: python --version

      - name: Run Pytest suite
        run: pytest python/tests

  unit_tests_ubuntu_local:
    name: Unit Testing (Ubuntu) (Local TZ)
    needs: lint_stylecheck
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone Europe/Amsterdam

      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e 'python[python,dev]'

      - name: Display Python version
        run: python --version

      - name: Run Pytest suite
        run: pytest python/tests

  unit_tests_ubuntu_typechecked:
    name: Typechecked Unit Testing (Ubuntu)
    needs: lint_stylecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e python[python,dev,docs]

      - name: Run Pytest suite
        env:
          HOPSWORKS_RUN_WITH_TYPECHECK: "true"
        run: pytest python/tests
        continue-on-error: true

  unit_tests_windows_utc:
    name: Unit Testing (Windows)
    needs: lint_stylecheck
    runs-on: windows-latest

    steps:
      - name: Set Timezone
        run: tzutil /s "UTC"

      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e python[python,dev]

      - name: Display Python version
        run: python --version

      - name: Run Pytest suite
        run: pytest python/tests

  unit_tests_windows_local:
    name: Unit Testing (Windows) (Local TZ)
    needs: lint_stylecheck
    runs-on: windows-latest

    steps:
      - name: Set Timezone
        run: tzutil /s "W. Europe Standard Time"

      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md python/

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "python/setup.py"
      - run: pip install -e python[python,dev]

      - name: Display Python version
        run: python --version

      - name: Display pip freeze
        run: pip freeze

      - name: Run Pytest suite
        run: pytest python/tests
